<?php
session_start();
header('Content-type:text/html;charset=utf-8');
define('DB_HOST','localhost');
define('DB_USER','aten');
define('DB_PWD','123456');
define('DB_NAME','test_bbs');
define('DB_PORT',3306);
?>